name: Build and Deploy to AWS

on:
  push:
    branches:
      - main  # or any other branch you want to deploy from

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'  # choose the node version that matches your development environment

      - name: Install dependencies
        run: npm install
        working-directory: ./naturesclock/
        
      - name: Install Angular CLI
        run: npm install -g @angular/cli
        working-directory: ./naturesclock/
      
      - name: Create env.js file
        run: |
          echo "window.env = {" > ./src/assets/env.js
          echo "  COGNITO_DOMAIN: '${{ secrets.COGNITO_DOMAIN }}'," >> ./src/assets/env.js
          echo "  CLIENT_ID: '${{ secrets.CLIENT_ID }}'," >> ./src/assets/env.js
          echo "  REDIRECT_URI: '${{ secrets.REDIRECT_URI }}'" >> ./src/assets/env.js
          echo "};" >> ./src/assets/env.js
        working-directory: ./naturesclock/

      - name: Build
        run: ng build --configuration=production
        working-directory: ./naturesclock/

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://natures-clock-s3 --delete
        working-directory: ./naturesclock/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-2'  # example: us-east-1

      - name: Invalidate CloudFront Distribution
        run: aws cloudfront create-invalidation --distribution-id E3P8D2HGJRGA3W --paths '/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-2'  # example: us-east-1
